# General server configuration
server:
  port: ${APPl_SERVER_PORT:8080}

# Database configuration
spring:
  datasource:
    url: ${APPl_DATASOURCE_JDBC_URL}
    driverClassName: org.postgresql.Driver
    username: ${APPL_DATASOURCE_USERNAME}
    password: ${APPL_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false

# Logging configuration
logging:
  level:
    org.atmosphere: WARN
