# General server configuration
server:
  port: ${APPl_SERVER_PORT:8080}

# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_anxiety
    driverClassName: org.postgresql.Driver
    username: social_anxiety
    password: social_anxiety_password
  jpa:
    hibernate:
      ddl-auto: validate

# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false

# Logging configuration
logging:
  level:
    org.atmosphere: WARN
