# Database configuration
spring:
  datasource:
    url: jdbc:postgres:localhost:5432/social_anxiety
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql=true
    hibernate.ddl-auto=create-drop
