language: java
dist: bionic

install: skip
os: linux

if: tag is blank

notifications:
  email: false

addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
  sonarcloud:
    organization: "zeroplexer"
    token:
      secure: "uNQvxJ+5icIOybiWdcOLdy3Ysyfzfw3XADqwxV5P2p/8N86hOJFhGWpzEgW9khpBK+dKSUPmUfWX2I7gll8R4ZGX5xQ6nO0y5E784afi5u/HPGRCrYLyPBD9pANLZyRmrfhWVia8r+/pN+t0pgEi/cvAkbqBQC3SlRTpog5XGjIjVC6IoNspdewoheTSHRqYIt8kLPckc0RNspoI8IiTUGBvVw+dpg+lxTr8iwjY6P1Oj39Bi0blDlab1EMLixYxauM0u3Kv+nu/6ncEk0aDhOqLqIsb7ykre1OgTukHjgA2V6z+DoJfKaMlJIxy3C61887ywhbZiYC94EW3/4b/9rFc5Lv03G/u7nYusC01GAOOH0GaKzxBgMkGm8m/SDnRgNuex7qAQmWF77Ic6OtYV6dq03/0+Nrfi5HiYhhkIVZnszwX2xShxzG+d3pHRa4P93BeeGqXOhTrkv0wELc7+2+QokzLcbKNN5G5ZcRdYy83Ius8oN87/iAxIQj0MjJoQ4NIya3ABWRvgUGckQ50gzDMRCOl6Tf8kfT7ICEVPVTxv/r5SsRRkQ+vjIhkPDNvqMgH0k4NYxp9YvW9rE8xJxcyqp2boDUlOzEwGCsHgmRA/ESVAV/S9leaTfXrzNLd72EkKXXtGUqmztJIuXfpTz6SEioLsraf62AYDo0wN2g="

jobs:
  include:
    # OracleJDK - Java 11 (lts, main build)
    - env: MAIN_BUILD='true'
      jdk: openjdk11
    # OpenJDK - Java 13 (latest)
    - env: MAIN_BUILD='false'
      jdk: openjdk13

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

before_script:
  - psql -c "CREATE DATABASE social_anxiety_integration;" -U postgres
  - psql -c "CREATE USER social_anxiety WITH PASSWORD 'social_anxiety_password';" -U postgres

script:
  - if [[ "${MAIN_BUILD}" != "" && "${MAIN_BUILD}" == "true" ]]; then export MAVEN_COMMAND="verify"; else export MAVEN_COMMAND="verify"; fi
  - mvn -f source/pom.xml versions:set -DnewVersion=${TRAVIS_BUILD_NUMBER}
  - mvn -f source/pom.xml ${MAVEN_COMMAND} sonar:sonar

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
