language: java
dist: bionic

install: skip
os: linux

if: tag is blank

notifications:
  email: false

addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

jobs:
  include:
    # OracleJDK - Java 11 (lts, main build)
    - env: MAIN_BUILD='true'
      jdk: openjdk11
    # OpenJDK - Java 13 (latest)
    - env: MAIN_BUILD='false'
      jdk: openjdk13

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

before_script:
  - psql -c "CREATE DATABASE social_anxiety_integration;" -U postgres
  - psql -c "CREATE USER social_anxiety WITH PASSWORD 'social_anxiety_password';" -U postgres

script:
  - if [[ "${MAIN_BUILD}" != "" && "${MAIN_BUILD}" == "true" ]]; then export MAVEN_COMMAND="verify"; else export MAVEN_COMMAND="verify"; fi
  - mvn -f source/pom.xml versions:set -DnewVersion=${TRAVIS_BUILD_NUMBER}
  - mvn -f source/pom.xml ${MAVEN_COMMAND}

cache:
  directories:
    - $HOME/.m2
